#ifndef PRISM_BINDINGS
#define PRISM_BINDINGS

#define PRISM_BINDING_FRAME    0
#define PRISM_BINDING_OBJECT   1
#define PRISM_BINDING_MATERIAL 2

#define PRISM_SHADOW_MAP0   3
#define PRISM_SHADOW_MAP1   4
#define PRISM_SHADOW_MAP2   5
#define PRISM_SHADOW_MAP3   6

#define PRISM_GEOMETRY_PASS_TEXTURE 7

#define PRISM_BINDING_TEXTURE 16

#endif
